### ISSUE TITLE
package.json run commands

### ISSUE THREAD

**Issue by artemderkach** [GorlifSense/rocket-snake#15]
change global call to local call:

mocha --> ./node_modules/.bin/_mocha

do for every package call

**Comment by Fleischers** [comment]
@ArtemDerkach But if it does not find global package, it should try local. This would be behaviour on server. It there anything wrong with this?

**Comment by artemderkach** [comment]
@Fleischers installing packages global takes additional time wile building image. also if new global variable added in project, it also should be added to build process, otherwise not.

**Comment by Fleischers** [comment]
@ArtemDerkach Do not install global packages. Instead, local package will be used if it is included to dependencies (currently in `dev`)
If new environment variable added, I believe it should be secured and not checked into VCS so would not be spoiled to public

**Comment by artemderkach** [comment]
@Fleischers why then `istanbul cover ./node_modules/.bin/_mocha` not `istanbulc cover mocha` ?

**Comment by Fleischers** [comment]
@ArtemDerkach There is an issue with default export object from `mocha`, so we use `_mocha` here.
https://github.com/gotwarlost/istanbul/issues/44

**Comment by artemderkach** [comment]
@Fleischers why not `istanbul cover _mocha` then ?

**Comment by Fleischers** [comment]
@ArtemDerkach I will try it, not sure it works like that

**Comment by artemderkach** [comment]
@Fleischers https://github.com/gotwarlost/istanbul/issues/44
